  steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/data-academy-project-411312/demo-app', 'app/']

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/data-academy-project-411312/demo-app']

  # Set up kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials autopilot-cluster-1 --zone europe-west1 --project data-academy-project-411312
        kubectl set image deployment/demo-app demo-app-container=europe-west1-docker.pkg.dev/data-academy-project-411312/demo-app

images:
  - 'europe-west1-docker.pkg.dev/data-academy-project-411312/demo-app'